param(
    [Parameter(Position=0)]
    [ValidateSet('validate','launch','generate','export','import','integrate','test-asset','preview','test-pipeline','scaffold','doctor','providers','asset-plan','asset-create','asset-process','provider-status','provider-execute','provider-poll','provider-fetch','provider-balance','provider-usage','provider-quote','multiview','comfy-start','comfy-stop','comfy-restart','comfy-status','image-4k','environment-test','environment-launch','world-test','world-launch','world-stress','world-benchmark')]
    [string]$Action = 'validate',
    [string]$Asset = 'test_fighter',
    [string]$GodotPath,
    [string]$BlenderPath,
    [switch]$Capture,
    [ValidateRange(0,3600)][int]$Frames = 0,
    [string]$RequestFile,
    [string]$Provider = 'auto',
    [string]$Job,
    [string]$Approval,
    [ValidateSet('prototype','background','standard','hero')][string]$Quality,
    [string]$SourceFile,
    [switch]$Repair
)
. "$PSScriptRoot/studio-common.ps1"
$runId = (Get-Date -Format 'yyyyMMdd-HHmmss-fff') + '-' + [guid]::NewGuid().ToString('N').Substring(0,6)
$script:RunDirectory = Get-StudioPath "generated/reports/$runId"
New-Item -ItemType Directory -Force -Path $script:RunDirectory | Out-Null
$outcome = 'FAIL'
$failure = $null
$assetConfig = $null
$godot = $null
$blender = $null
$gamePath = Get-StudioPath 'game'

function Import-Project {
    Invoke-StudioProcess 'godot-import' $godot @('--headless','--path',$gamePath,'--editor','--import')
}
function Generate-Asset {
    if ($assetConfig.PSObject.Properties['generation_method'] -and $assetConfig.generation_method -eq 'external_import') {
        throw 'External assets must use provider cleanup/export; do not replace them with a procedural generator.'
    }
    Invoke-StudioProcess 'blender-generate' $blender @('--background','--factory-startup','--python-exit-code','1','--python',(Get-StudioPath $assetConfig.generator),'--','--blend-only') 180 'PIPELINE_BLENDER_PASS'
    if (-not (Test-Path -LiteralPath (Get-StudioPath $assetConfig.blend))) { throw 'Generator did not save its editable Blender project.' }
}
function Export-Asset {
    Invoke-StudioProcess 'blender-export' $blender @('--background','--factory-startup',(Get-StudioPath $assetConfig.blend),'--python-exit-code','1','--python',(Get-StudioPath 'blender/scripts/export_glb.py'),'--','--output',(Get-StudioPath $assetConfig.model),'--uv-mode',$assetConfig.uv_mode) 180 'PIPELINE_GLB_PASS'
}
function Integrate-Asset {
    $scenePath = Get-StudioPath $assetConfig.scene
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $scenePath) | Out-Null
    $resourcePath = $assetConfig.model.Replace('game/', 'res://')
    $text = @"
; Generated by tools/pipeline.ps1. Put gameplay behavior in a parent scene.
[gd_scene load_steps=2 format=3]

[ext_resource type="PackedScene" path="$resourcePath" id="1_model"]

[node name="$Asset" type="Node3D"]

[node name="Model" parent="." instance=ExtResource("1_model")]
"@
    if ((Test-Path -LiteralPath $scenePath) -and -not (Get-Content -Raw -LiteralPath $scenePath).StartsWith('; Generated by tools/pipeline.ps1.')) {
        throw "Preserving hand-authored scene: $scenePath. Choose another integration path before regenerating."
    }
    [IO.File]::WriteAllText($scenePath, $text + "`n")
    Write-Host "Integrated: $scenePath"
}
function Test-Asset {
    Invoke-StudioProcess 'godot-asset-test' $godot @('--headless','--path',$gamePath,'--script','res://scripts/validate_asset.gd','--',"--manifest=$(Get-StudioPath "tools/assets/$Asset.json")") 90 'PIPELINE_ASSET_PASS'
}
function Validate-Project {
    Import-Project
    Invoke-StudioProcess 'godot-resource-test' $godot @('--headless','--path',$gamePath,'--script','res://scripts/validate_resources.gd') 90 'PIPELINE_RESOURCES_PASS'
    Invoke-StudioProcess 'godot-regression' $godot @('--headless','--path',$gamePath,'--script','res://scripts/validate_pipeline.gd') 90 'PIPELINE_SCENE_PASS'
    Invoke-StudioProcess 'godot-main-runtime' $godot @('--headless','--path',$gamePath,'--quit-after','120','--fixed-fps','60')
}
function Preview-Asset {
    $preview = Get-StudioPath "generated/previews/$Asset.png"
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $preview) | Out-Null
    Invoke-StudioProcess 'godot-preview' $godot @('--path',$gamePath,'res://scenes/asset_preview.tscn','--fixed-fps','60','--quit-after','300','--',"--asset=$($assetConfig.scene.Replace('game/','res://'))","--capture=$preview") 90 'PIPELINE_PREVIEW_PASS'
    if (-not (Test-Path -LiteralPath $preview)) { throw 'Missing rendered preview.' }
}

try {
    if ($Action.StartsWith('world-')) {
        $operation = @{ 'world-test'='test-gameplay'; 'world-launch'='launch'; 'world-stress'='stress'; 'world-benchmark'='benchmark' }[$Action]
        & (Get-StudioShell) -NoProfile -File "$PSScriptRoot/world.ps1" $operation
        if ($LASTEXITCODE -ne 0) { throw 'World operation failed' }
    } elseif ($Action -eq 'image-4k') {
        $python = Get-Command py -CommandType Application -ErrorAction Stop | Select-Object -First 1
        Invoke-StudioProcess 'image-4k' $python.Source @('-3.11',(Get-StudioPath 'tools/imagegen/high_resolution.py'),$RequestFile) 900
    } elseif ($Action.StartsWith('environment-')) {
        $operation = if ($Action -eq 'environment-launch') { 'launch' } else { 'build' }
        & (Get-StudioShell) -NoProfile -File "$PSScriptRoot/environment.ps1" $operation
        if ($LASTEXITCODE -ne 0) { throw 'Environment operation failed' }
    } elseif ($Action.StartsWith('comfy-')) {
        $python = Get-Command py -CommandType Application -ErrorAction Stop | Select-Object -First 1
        Invoke-StudioProcess 'comfy-backend' $python.Source @('-3.11',(Get-StudioPath 'tools/imagegen/backend.py'),$Action.Replace('comfy-','')) 150
        Get-Content -LiteralPath (Join-Path $script:RunDirectory 'comfy-backend.log')
    } elseif ($Action -in @('providers','asset-create','asset-plan','asset-process','multiview') -or $Action.StartsWith('provider-')) {
        $python = Get-Command py -CommandType Application -ErrorAction Stop | Select-Object -First 1
        $providerArgs = @('-3.11', (Get-StudioPath 'tools/providers/cli.py'))
        if ($Action -eq 'providers') { $providerArgs += 'providers' }
        elseif ($Action -in @('asset-create','asset-plan','multiview')) {
            $providerArgs += @($Action.Replace('asset-', ''),'--request',$RequestFile,'--provider',$Provider)
            if ($Quality) { $providerArgs += @('--quality',$Quality) }
        }
        elseif ($Action -eq 'asset-process') {
            $providerArgs += @('process','--job',$Job)
            if ($SourceFile) { $providerArgs += @('--source',$SourceFile) }
            if ($Repair) { $providerArgs += '--repair' }
        }
        else {
            $providerArgs += $Action.Replace('provider-', '')
            if ($Job) { $providerArgs += @('--job',$Job) }
            if ($Approval) { $providerArgs += @('--approval',$Approval) }
            if ($Provider -ne 'auto') { $providerArgs += @('--provider',$Provider) }
        }
        Invoke-StudioProcess 'provider-command' $python.Source $providerArgs 600
        Get-Content -LiteralPath (Join-Path $script:RunDirectory 'provider-command.log')
    } elseif ($Action -eq 'doctor') {
        & "$PSScriptRoot/inspect-local.ps1" -OutputDirectory $script:RunDirectory
    } elseif ($Action -eq 'scaffold') {
        if ($Asset -notmatch '^[a-z][a-z0-9_]{0,63}$') { throw 'Invalid asset ID.' }
        $files = @{
            "tools/assets/$Asset.json" = 'tools/templates/asset.json.template'
            "docs/assets/$Asset.md" = 'tools/templates/asset-spec.md.template'
            "blender/scripts/generate_$Asset.py" = 'blender/scripts/templates/generate_asset.py.template'
        }
        foreach ($destination in $files.Keys) {
            if (Test-Path -LiteralPath (Get-StudioPath $destination)) { throw "Scaffold refuses to overwrite $destination" }
        }
        foreach ($destination in $files.Keys) {
            $path = Get-StudioPath $destination
            New-Item -ItemType Directory -Force -Path (Split-Path -Parent $path) | Out-Null
            $content = (Get-Content -Raw -LiteralPath (Get-StudioPath $files[$destination])).Replace('__ASSET_ID__', $Asset)
            [IO.File]::WriteAllText($path, $content)
        }
        Write-Host "Draft scaffold created for $Asset. Author its design and procedural generator before marking it ready."
    } else {
        if ($Action -notin @('generate','export')) { $godot = Resolve-StudioTool 'godot' $GodotPath }
        if ($Action -in @('generate','export','test-pipeline')) { $blender = Resolve-StudioTool 'blender' $BlenderPath }
        if ($Action -notin @('validate','launch','import') -or $Capture) { $assetConfig = Read-StudioAsset $Asset }
        switch ($Action) {
            'generate' { Generate-Asset }
            'export' { Export-Asset }
            'import' { Import-Project }
            'integrate' { Integrate-Asset; Import-Project; Test-Asset }
            'test-asset' { Import-Project; Test-Asset }
            'preview' { Import-Project; Test-Asset; Preview-Asset }
            'validate' { Validate-Project; if ($Capture) { Test-Asset; Preview-Asset } }
            'test-pipeline' { Generate-Asset; Export-Asset; Integrate-Asset; Validate-Project; Test-Asset; Preview-Asset }
            'launch' {
                Import-Project
                if ($Frames -gt 0) {
                    Invoke-StudioProcess 'godot-launch-test' $godot @('--path',$gamePath,'--quit-after',"$Frames",'--fixed-fps','60')
                } else {
                    $start = [Diagnostics.ProcessStartInfo]::new()
                    $start.FileName = $godot
                    $start.UseShellExecute = $false
                    $start.CreateNoWindow = $true
                    $start.ArgumentList.Add('--path')
                    $start.ArgumentList.Add($gamePath)
                    $gameProcess = [Diagnostics.Process]::Start($start)
                    Write-Host "Game launched (PID $($gameProcess.Id)). Use Escape to close the current demo."
                    $gameProcess.Dispose()
                }
            }
        }
    }
    $outcome = 'PASS'
    Write-Host "PIPELINE_PASS: $Action"
} catch {
    $failure = $_.Exception.Message
    Write-Host "PIPELINE_FAIL: $failure"
} finally {
    $report = [ordered]@{schema_version=1; action=$Action; asset=$Asset; status=$outcome; error=$failure; utc=[DateTime]::UtcNow.ToString('o'); stages=@($script:StudioStages.ToArray())}
    $reportPath = Join-Path $script:RunDirectory 'report.json'
    $report | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $reportPath
    Write-Host "Report: $reportPath"
}
if ($outcome -ne 'PASS') { exit 1 }
